from selenium.webdriver.common.by import By


class MainPageLocators(object):
    """A class for main page locators. All main page locators should come here"""

    OurStoryTest = (By.CSS_SELECTOR, '.component:nth-child(4) .promo-body > p')
    TheDmcFamily = (By.CSS_SELECTOR, '.small-text:nth-child(2)')
    NextButton = (By.CSS_SELECTOR, '.next-text')
    RotatingText1 = (By.CSS_SELECTOR, '.slide:nth-child(1) p')
    RotatingText2 = (By.CSS_SELECTOR, '.slide:nth-child(2) p')
    RotatingText3 = (By.CSS_SELECTOR, '.slide:nth-child(3) p')
    DynaLink = (By.CSS_SELECTOR, ".dyna-theme .promo-image-logo-link_image-link")
    NobelLink = (By.CSS_SELECTOR, ".nobel-theme .promo-image-logo-link_image-link")
    OurStoryLink = (By.CSS_SELECTOR, '.jump-parent a')
    OurCompaniesLink = (By.CSS_SELECTOR, '.level1:nth-child(3) a')
    InvestorsLink = (By.CSS_SELECTOR, '.level1:nth-child(4) a')
    SearchButton = (By.CSS_SELECTOR, '.navigation-main-search-icon')
    TextField = (By.NAME, 'textBoxSearch')
    SearchResults = (By.CSS_SELECTOR, '.results-count')
    UpButton = (By.CSS_SELECTOR, '.to-top')


class OurStoryPageLocators(object):
    MainText = (By.CSS_SELECTOR, '.component:nth-child(3) span')
    SubImageText = (By.CSS_SELECTOR, '.row:nth-child(8) span')
    MediumTextS = (By.CSS_SELECTOR, '.medium-text')
    Values1 = (By.CSS_SELECTOR, '.col-12:nth-child(1) > .row .promo-text-numbered__body > span')
    Values2 = (By.CSS_SELECTOR, '.col-12:nth-child(2) > .row span')
    Values3 = (By.CSS_SELECTOR, '.col-12:nth-child(3) .promo-text-numbered__body')
    Values4 = (By.CSS_SELECTOR, '.col-12:nth-child(4) .promo-text-numbered__body')
    BottomText = (By.CSS_SELECTOR, '.row:nth-child(16) span')
    Picture1 = (By.CSS_SELECTOR, '.jump-parent a')
    Picture2 = (By.CSS_SELECTOR, '.margin-bottom-half img')
    SubmitButton = (By.CSS_SELECTOR, '.button')
    TextField = (By.ID, 'email')
    ConsentButton = (By.CSS_SELECTOR, '#compile66976 > span')
    Confirmation = (By.CSS_SELECTOR, '.\_label')
    ClearCookies = (By.CSS_SELECTOR, '.submit > a')
    SubLink1 = (By.LINK_TEXT, 'Overview')
    SubLink2 = (By.LINK_TEXT, 'Our Culture')
    SubLink3 = (By.LINK_TEXT, 'Performance Tenets')


class OurCompaniesLocators(object):
    MainText1 = (By.CSS_SELECTOR, '.component-content > p:nth-child(1)')
    MainText2 = (By.CSS_SELECTOR, '.component-content > p:nth-child(2)')
    MainText3 = (By.CSS_SELECTOR, 'p:nth-child(3)')
    DMCFamilyText = (By.CSS_SELECTOR, '.promo-text-link__body')
    DynaLink = (By.CSS_SELECTOR, '.dyna-theme .promo-image-logo-link_image-link')
    NobelLink = (By.CSS_SELECTOR, '.nobel-theme .promo-image-logo-link_image-link')
    ContactUsLink = (By.LINK_TEXT, 'Contact Us')
    DynaText1 = (By.CSS_SELECTOR, '.promo-image-vertical__body > p:nth-child(1)')
    DynaText2 = (By.CSS_SELECTOR, '.promo-image-vertical__body > p:nth-child(2)')
    DynaTextLink = (By.LINK_TEXT, 'Visit Website')
    DynaBullet2 = (By.CSS_SELECTOR, ' .sxa-bullets:nth-child(2)')
    DynaBullet3 = (By.CSS_SELECTOR, ' .sxa-bullets:nth-child(3)')
    DynaBullet4 = (By.CSS_SELECTOR, ' .sxa-bullets:nth-child(4)')
    Images = (By.CLASS_NAME, 'field-slideimage')
    NobelText1 = (By.CSS_SELECTOR, '.nobel-theme .promo-image-vertical__body')
    NobelTextLink = (By.CSS_SELECTOR, '.nobel-theme .promo-image-vertical__arrow-link a')
    NobelBullet2 = (By.CSS_SELECTOR, '.row:nth-child(15) .sxa-bullets:nth-child(2)')
    NobelBullet3 = (By.CSS_SELECTOR, '.row:nth-child(15) .sxa-bullets:nth-child(3)')
    ClearCookies = (By.CSS_SELECTOR, '.submit > a')
    SubLink1 = (By.LINK_TEXT, 'Overview')
    SubLink2 = (By.LINK_TEXT, 'The DMC Family')
    SubLink3 = (By.LINK_TEXT, 'DynaEnergetics')
    SubLink4 = (By.LINK_TEXT, 'NobelClad')


class InvestorsLocators(object):
    MainText = (By.CSS_SELECTOR, '.col-12:nth-child(1) .component > .component-content > .promo-body')
    picture1 = (By.CSS_SELECTOR, '.col-6:nth-child(1) img')
    picture2 = (By.CSS_SELECTOR, '.col-6:nth-child(2) img')
    picture3 = (By.CSS_SELECTOR, '.col-6:nth-child(3) img')
    picture4 = (By.CSS_SELECTOR, '.col-6:nth-child(4) img')
    LinkText1 = (By.CSS_SELECTOR, 'a:nth-child(2) > .event-details > p:nth-child(2)')
    LinkText2 = (By.CSS_SELECTOR, 'a:nth-child(3) > .event-details > p:nth-child(2)')
    Title = (By.CSS_SELECTOR, '.component:nth-child(2) > .component-content > div > .field-section-title')
    RecentNewsText1 = (By.CSS_SELECTOR, 'li:nth-child(1) .investors-recent-news__title')
    RecentNewsText2 = (By.CSS_SELECTOR, 'li:nth-child(2) .investors-recent-news__title')
    RecentNewsText3 = (By.CSS_SELECTOR, 'li:nth-child(3) .investors-recent-news__title')
    RecentNewsText4 = (By.CSS_SELECTOR, 'li:nth-child(4) .investors-recent-news__title')
    NextButton = (By.CSS_SELECTOR, '.page-selector-item-next > a')
    LowerText1 = (By.CSS_SELECTOR, '.component-content > .promo .small-text')
    LowerText2 = (By.CSS_SELECTOR, '.col-12:nth-child(2) .small-text:nth-child(2)')
    LowerText3 = (By.CSS_SELECTOR, '.col-12:nth-child(3) .small-text:nth-child(1)')
    LowerText4 = (By.CSS_SELECTOR, '.col-12:nth-child(4) .small-text:nth-child(2)')
    LowerText5 = (By.CSS_SELECTOR, '.col-12:nth-child(5) .small-text')
    SubLink1 = (By.CSS_SELECTOR, '.hide-desktop-link a')
    SubLink2 = (By.CSS_SELECTOR, '.jump-parent a')
    SubLink3 = (By.CSS_SELECTOR, '.level2:nth-child(3) a')
    SubLink4 = (By.CSS_SELECTOR, '.level2:nth-child(4) a')
    SubLink5 = (By.CSS_SELECTOR, '.level2:nth-child(5) a')
    SubLink6 = (By.CSS_SELECTOR, '.level2:nth-child(6) a')
    SubLink7 = (By.CSS_SELECTOR, '.level2:nth-child(7) a')
    NewsCount = (By.ID, 'irNewsCount')
    NewsStory1 = (By.CSS_SELECTOR, '#ir-direct-news > li:nth-child(3)')
    NewsStory2 = (By.CSS_SELECTOR, '#ir-direct-news > li:nth-child(9)')
    LoadMore = (By.ID, 'irDirectNewsButton')
    CompanyInfoMainText = (By.CSS_SELECTOR, '.small-text > span')
    Biography1 = (By.CSS_SELECTOR, '.row:nth-child(7) .promo-biography__body')
    ShareholderResults = (By.CSS_SELECTOR, '.results-count')
    ShareholderLetter = (By.CSS_SELECTOR, 'li:nth-child(5) .shareholder-letters__title')
    SubName1 = (By.CSS_SELECTOR, '.row:nth-child(4) > .col-6:nth-child(1) .small-text')
    SubName2 = (By.CSS_SELECTOR, '.row:nth-child(6) .small-text')
    SecResultsCount = (By.ID, 'sec-fillings-result-count')
    LoadMoreSEC = (By.ID, 'loadMore')
    SECResult1 = (By.CSS_SELECTOR, '.odd:nth-child(1) > td:nth-child(2)')
    SECResult2 = (By.CSS_SELECTOR, '.odd:nth-child(15) > td:nth-child(2)')
    GovernanceBio1 = (By.CSS_SELECTOR, '.component:nth-child(3) .promo-biography__body:nth-child(2)')
    GovernanceBio2 = (By.CSS_SELECTOR, '.component:nth-child(4) .promo-biography__body:nth-child(2)')


class NewsSustainabilityLocators(object):
    Results = (By.CSS_SELECTOR, '.results-count')
    News1 = (By.CSS_SELECTOR, 'li:nth-child(1) .news-results__title')
    News2 = (By.CSS_SELECTOR, 'li:nth-child(30) .news-results__title')
    LoadMore = (By.CSS_SELECTOR, 'body.default-device.bodyclass:nth-child(2) div.container div.row div.component.snippe'
                                 't.col-12.snippet--dmcglobal.cd.snippet--dmcglobal.cd.initialized:nth-child(2) div.com'
                                 'ponent-content div.snippet-inner div.snippet-container div.snippet.initialized div.r'
                                 'ow div.component.load-more.col-12.load-more--dmcglobal.cd.load-more--dmcglobal.cd:nt'
                                 'h-child(3) > div.component-content')
    SustainabilityLink = (By.CSS_SELECTOR, '.level1:nth-child(6) a')
    SustainabilityText = (By.CSS_SELECTOR, 'p:nth-child(1)')
    SustainabilityDoc = (By.LINK_TEXT, 'DMC 2020 SUSTAINABILITY REPORT')


class ContactUsLocators(object):
    Text1 = (By.CSS_SELECTOR, '.component:nth-child(1) .promo-body > p:nth-child(1)')
    Text2 = (By.CSS_SELECTOR, '.component:nth-child(1) p:nth-child(2)')
    Results = (By.CSS_SELECTOR, '.facet-dropdown > .component-content')
    Contact1 = (By.CSS_SELECTOR, 'li:nth-child(1) .office-location-result__name')
    Contact2 = (By.CSS_SELECTOR, 'li:nth-child(11) .office-location-result__name')
